name: VirtualRedstone
main: com.johncorby.virtualredstone.VirtualRedstone
version: 0.5
author: JohnCorby
description: Plugin for my server
depend: [PlugMan]

commands:
  virtualredstone:
    description: Base VirtualRedstone command.
    aliases: vrs

permissions:
  virtualredstone.admin:
    description: You can do everything.
    default: op
