#Sequencers:
#  Name:
#    Sequence:
#      - o0
#    IOs:
#      0:
#        Output: x, y, z
#        Outputs:
#          - x, y, z
#Tables:
#  Name:
#    Table:
#      - i0, o0
#    I/Os:
#      0:
#        Inputs:
#          - x, y, z
#        Outputs:
#          - x, y, z
#
#Sign:
#  type (seq/tab + in/out)
#  seq/tab name
#  instance num
#  in/out num


Sequencers: {}
Tables: {}
