name: VirtualRedstone
main: com.johncorby.virtualredstone.VirtualRedstone
version: 1.0
author: JohnCorby
description: Plugin for my server
depend: [PlugMan]

commands:
    virtualredstone:
        description: Base VirtualRedstone command.
        aliases: vrs

permissions:
    vrs.admin:
        description: You can do everything.
        default: false
