name: VirtualRedstone
main: com.johncorby.virtualredstone.VirtualRedstone
version: 1.0
author: JohnCorby
description: Plugin for my server
depend: [FastAsyncWorldEdit, PlugMan]

commands:
    virtualredstone:
        description: Base VirtualRedstone command.
        aliases: vr

permissions:
    vr.admin:
        description: You can do everything.
        default: false
